
- hosts: all
  become: true
  tasks:
     
     - name: update repository index     
       apt: 
         update_cache: true
       when: ansible_distribution_version == "Ubuntu"

     - name: installing apache2
       apt:
         name: apache2
         state: latest
       when: ansible_distribution == "Ubuntu"

     - name: add php support for apache
       apt:
         name: libapache2-mod-php
         state: latest
       when: ansible_distribution == "Ubuntu"


     - name: update repository index
       yum:
         update_cache: true
       when: ansible_distribution_version == "CentOS"

     - name: installing httpd
       yum:
         name: httpd
         state: latest
       when: ansible_distribution == "CentOS"

     - name: add php support for apache
       yum:
         name: php
         state: latest
       when: ansible_distribution == "CentOS"


