
- hosts: all
  become: true
  tasks:

     - name: installing apache, php and updating respository index
       package:
         name:
           - "{{ apache_package }}"
           - "{{ php_package }}"
         state: latest
         update_cache: yes
      
