---

- hosts: all
  become: true
  pre_tasks:
     
  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


   
  - name: install update (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"



- hosts: web_servers
  become: true
  tasks:
      


  - name: installing apache2 and php for ubuntu 
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"    

  - name: installing  php for centos servers
    tags: apache,httpd,centos
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
         


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: db,mariadb,centos
    yum:
      name: mariadb
      state: latest 
    when: ansible_distribution == "CentOS"


  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: installing samba package
    tags: samba
    package:
      name: samba
      state: latest

